# Generated by Django 4.2.7 on 2023-12-06 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_menu_menu_item_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="comment",
        ),
        migrations.AddField(
            model_name="booking",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 6, 15, 18, 47, 176378, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
