# Generated by Django 4.2.7 on 2023-12-06 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_remove_booking_comment_booking_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
