# Generated by Django 4.2.8 on 2023-12-06 23:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0007_alter_booking_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
